INSERT INTO regions (code,name,level,parent_code,lat,lng) VALUES
('11','Aceh','provinsi','',0,0),
('12','Sumatera Utara','provinsi','',0,0),
('13','Sumatera Barat','provinsi','',0,0),
('14','Riau','provinsi','',0,0),
('15','Jambi','provinsi','',0,0),
('16','Sumatera Selatan','provinsi','',0,0),
('17','Bengkulu','provinsi','',0,0),
('18','Lampung','provinsi','',0,0),
('19','Kepulauan Bangka Belitung','provinsi','',0,0),
('21','Kepulauan Riau','provinsi','',0,0),
('31','DKI Jakarta','provinsi','',0,0),
('32','Jawa Barat','provinsi','',0,0),
('33','Jawa Tengah','provinsi','',0,0),
('34','DI Yogyakarta','provinsi','',0,0),
('35','Jawa Timur','provinsi','',0,0),
('36','Banten','provinsi','',0,0),
('51','Bali','provinsi','',0,0),
('52','Nusa Tenggara Barat','provinsi','',0,0),
('53','Nusa Tenggara Timur','provinsi','',0,0),
('61','Kalimantan Barat','provinsi','',0,0),
('62','Kalimantan Tengah','provinsi','',0,0),
('63','Kalimantan Selatan','provinsi','',0,0),
('64','Kalimantan Timur','provinsi','',0,0),
('65','Kalimantan Utara','provinsi','',0,0),
('71','Sulawesi Utara','provinsi','',0,0),
('72','Sulawesi Tengah','provinsi','',0,0),
('73','Sulawesi Selatan','provinsi','',0,0),
('74','Sulawesi Tenggara','provinsi','',0,0),
('75','Gorontalo','provinsi','',0,0),
('76','Sulawesi Barat','provinsi','',0,0),
('81','Maluku','provinsi','',0,0),
('82','Maluku Utara','provinsi','',0,0),
('91','Papua Barat','provinsi','',0,0),
('92','Papua','provinsi','',0,0),
('93','Papua Selatan','provinsi','',0,0),
('94','Papua Tengah','provinsi','',0,0),
('95','Papua Pegunungan','provinsi','',0,0),
('96','Papua Barat Daya','provinsi','',0,0);
